[package]
name = "query-gateway"
version = "1.0.8"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.7"
base64 = "0.22"
chrono = "0.4"
clap = { version = "4", features = ["derive", "env"] }
derivative = "2"
dotenv = "0.15"
duration-string = { version = "0.4", features = ["serde"] }
env_logger = "0.11"
flate2 = "1"
futures = "0.3"
lazy_static = "1"
log = "0.4"
prometheus = "0.13"
rand = "0.8"
rusqlite = { version = "0.31", features = ["trace", "bundled"] }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_with = "3"
serde_yaml = "0.9"
tabled = "0.15"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tokio-rusqlite = "0.5"
uuid = { version = "1", features = ["v4", "fast-rng"] }

contract-client = { git = "https://github.com/subsquid/subsquid-network.git", version = "1.0.4" }
subsquid-messages = { git = "https://github.com/subsquid/subsquid-network.git", version = "1.1.1", features = ["semver"] }
subsquid-network-transport = { git = "https://github.com/subsquid/subsquid-network.git", version = "1.0.14", features = ["gateway"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"
