worker_inactive_threshold_sec: 120
min_worker_priority: -4
max_worker_priority: 2
default_buffer_size: 10
default_chunk_timeout_sec: 30
default_backoff_sec: 1
default_request_multiplier: 1
default_retries: 3
available_datasets:
  ethereum-mainnet: "s3://ethereum-mainnet"
