logs_collector_id: "12D3KooWFnRhNqgsKtsDDhsozaWuyrTvtQA2Eu4XWvSPRd4UZynd"
send_metrics: true
worker_inactive_threshold_sec: 120
worker_greylist_time_sec: 1800
default_query_timeout_sec: 60
summary_print_interval_sec: 30
workers_update_interval_sec: 180
available_datasets:
  0g-testnet: czM6Ly8wZy10ZXN0bmV0LXRyYWNlbGVzcy0x
  aleph-zero-evm-mainnet: czM6Ly9hbGVwaC16ZXJvLWV2bS1tYWlubmV0
  arbitrum-nova: czM6Ly9hcmJpdHJ1bS1ub3ZhLTE
  arbitrum-one: czM6Ly9hcmJpdHJ1bS1vbmU
  arbitrum-sepolia: czM6Ly9hcmJpdHJ1bS1zZXBvbGlhLXRyYWNlbGVzcw
  arthera-mainnet: czM6Ly9hcnRoZXJhLW1haW5uZXQ
  astar-mainnet: czM6Ly9hc3Rhci1tYWlubmV0LXRyYWNlbGVzcy0x
  astar-zkyoto: czM6Ly9hc3Rhci16a3lvdG8tMS10cmFjZWxlc3M
  astar-zkevm-mainnet: czM6Ly9hc3Rhci16a2V2bS1tYWlubmV0LTEtdHJhY2VsZXNz
  avalanche-mainnet: czM6Ly9hdmEtbWFpbm5ldC0x
  avalanche-testnet: czM6Ly9hdmEtdGVzdG5ldC0x
  b3-sepolia: czM6Ly9iMy1zZXBvbGlh
  b3-mainnet: czM6Ly9iMy1tYWlubmV0
  base-mainnet: czM6Ly9iYXNl
  base-sepolia: czM6Ly9iYXNlLXNlcG9saWE
  berachain-bartio: czM6Ly9iZXJhY2hhaW4tYmFydGlv
  binance-mainnet: czM6Ly9iaW5hbmNlLW1haW5uZXQ
  binance-testnet: czM6Ly9iaW5hbmNlLXRlc3RuZXQtdHJhY2VsZXNzLTE
  bitfinity-mainnet: czM6Ly9iaXRmaW5pdHktbWFpbm5ldA
  bitfinity-testnet: czM6Ly9iaXRmaW5pdHktdGVzdG5ldA
  blast-l2-mainnet: czM6Ly9ibGFzdC1sMi1tYWlubmV0LTE
  blast-sepolia: czM6Ly9ibGFzdC1zZXBvbGlhLTEtdHJhY2VsZXNz
  bitgert-mainnet: czM6Ly9iaXRnZXJ0LW1haW5uZXQtMQ
  bitgert-testnet: czM6Ly9iaXRnZXJ0LXRlc3RuZXQtMQ
  bob-mainnet: czM6Ly9ib2ItbWFpbm5ldA
  canto: czM6Ly9jYW50by10cmFjZWxlc3M
  canto-testnet: czM6Ly9jYW50by10ZXN0bmV0LXRyYWNlbGVzcw
  core-mainnet: czM6Ly9jb3JlLW1haW5uZXQtMQ
  cyberconnect-l2-testnet: czM6Ly9jeWJlci1sMi10ZXN0bmV0LTI
  cyber-mainnet: czM6Ly9jeWJlci1tYWlubmV0LTE
  crossfi-testnet: czM6Ly9jcm9zc2ZpLXRlc3RuZXQtdHJhY2VsZXNz
  dfk-chain: czM6Ly9kZmstY2hhaW4tdHJhY2VsZXNzLTE
  dogechain-mainnet: czM6Ly9kb2dlY2hhaW4tbWFpbm5ldC10cmFjZWxlc3MtMQ
  dogechain-testnet: czM6Ly9kb2dlY2hhaW4tdGVzdG5ldC10cmFjZWxlc3MtMQ
  ethereum-holesky: czM6Ly9ldGhlcmV1bS1ob2xlc2t5LTE
  ethereum-mainnet: czM6Ly9ldGhlcmV1bS1tYWlubmV0
  ethereum-sepolia: czM6Ly9ldGhlcmV1bS1zZXBvbGlhLTE
  etherlink-mainnet: czM6Ly9ldGhlcmxpbmstbWFpbm5ldC10cmFjZWxlc3M
  etherlink-testnet: czM6Ly9ldGhlcmxpbmstdGVzdG5ldC0zLXRyYWNlbGVzcw
  exosama: czM6Ly9leG9zYW1hLTE
  fantom-mainnet: czM6Ly9mYW50b20tbWFpbm5ldC10cmFjZWxlc3M
  fantom-testnet: czM6Ly9mYW50b20tdGVzdG5ldC10cmFjZWxlc3MtMQ
  flare-mainnet: czM6Ly9mbGFyZS1tYWlubmV0LXRyYWNlbGVzcy0x
  galxe-gravity: czM6Ly9nYWx4ZS1ncmF2aXR5
  gelato-arbitrum-blueberry: czM6Ly9hcmJpdHJ1bS1ibHVlYmVycnktMQ
  gelato-opcelestia-raspberry: czM6Ly9vcGNlbGVzdGlhLXJhc3BiZXJyeS10cmFjZWxlc3M
  gnosis-mainnet: czM6Ly9nbm9zaXMtbWFpbm5ldC0x
  immutable-zkevm-mainnet: czM6Ly9pbW11dGFibGUtemtldm0tbWFpbm5ldC10cmFjZWxlc3MtMQ
  immutable-zkevm-testnet: czM6Ly9pbW11dGFibGUtemtldm0tdGVzdG5ldC10cmFjZWxlc3MtMQ
  kyoto-testnet: czM6Ly9reW90by10ZXN0bmV0LXRyYWNlbGVzcw
  linea-mainnet: czM6Ly9saW5lYS1tYWlubmV0LTE
  manta-pacific: czM6Ly9tYW50YS1wYWNpZmljLXRyYWNlbGVzcw
  manta-pacific-sepolia: czM6Ly9tYW50YS1wYWNpZmljLXNlcG9saWE
  mantle-mainnet: czM6Ly9tYW50bGUtbWFpbm5ldC0xLXRyYWNlbGVzcw
  mantle-sepolia: czM6Ly9tYW50bGUtc2Vwb2xpYS0xLXRyYWNlbGVzcw
  merlin-mainnet: czM6Ly9tZXJsaW4tbWFpbm5ldC10cmFjZWxlc3M
  merlin-testnet: czM6Ly9tZXJsaW4tdGVzdG5ldC10cmFjZWxlc3M
  metis-mainnet: czM6Ly9tZXRpcy1tYWlubmV0LTM
  mode-mainnet: czM6Ly9tb2RlLW1haW5uZXQtdHJhY2VsZXNz
  moonbase-testnet: czM6Ly9tb29uYmFzZS10ZXN0bmV0LTE
  moonbeam-mainnet: czM6Ly9tb29uYmVhbS1ldm0tMg
  moonriver-mainnet: czM6Ly9tb29ucml2ZXItbWFpbm5ldC0x
  moonsama: czM6Ly9tb29uc2FtYS10cmFjZWxlc3MtMQ
  nakachain: czM6Ly9uYWthY2hhaW4
  neon-mainnet: czM6Ly9uZW9uLW1haW5uZXQtdHJhY2VsZXNz
  neon-devnet: czM6Ly9uZW9uLWRldm5ldC10cmFjZWxlc3MtMQ
  neox-testnet: czM6Ly9uZW94LXRlc3RuZXQ
  opbnb-mainnet: czM6Ly9vcGJuYi1tYWlubmV0LXRyYWNlbGVzcy0x
  opbnb-testnet: czM6Ly9vcGJuYi10ZXN0bmV0LXRyYWNlbGVzcy0x
  optimism-mainnet: czM6Ly9vcHRpbWlzbS0y
  optimism-sepolia: czM6Ly9vcHRpbWlzbS1zZXBvbGlhLXRyYWNlbGVzcw
  peaq-mainnet: czM6Ly9wZWFxLW1haW5uZXQtdHJhY2VsZXNzLTE
  plume-testnet: czM6Ly9wbHVtZS10ZXN0bmV0
  plume-devnet: czM6Ly9wbHVtZS1kZXZuZXQ
  polygon-mainnet: czM6Ly9wb2x5Z29uLW1haW5uZXQtMQ
  polygon-amoy-testnet: czM6Ly9wb2x5Z29uLWFtb3ktdGVzdG5ldC10cmFjZWxlc3M
  polygon-zkevm-mainnet: czM6Ly9wb2x5Z29uLXprZXZtLW1haW5uZXQtdHJhY2VsZXNz
  polygon-zkevm-cardona-testnet: czM6Ly9wb2x5Z29uLXprZXZtLWNhcmRvbmEtdGVzdG5ldC10cmFjZWxlc3MtMQ
  prom-testnet: czM6Ly9wcm9tLXRlc3RuZXQtMS10cmFjZWxlc3M
  prom-testnet-v2: czM6Ly9wcm9tLXRlc3RuZXQtdjI
  puppynet: czM6Ly9wdXBweW5ldA
  scroll-mainnet: czM6Ly9zY3JvbGwtbWFpbm5ldA
  scroll-sepolia: czM6Ly9zY3JvbGwtc2Vwb2xpYQ
  shiden-mainnet: czM6Ly9zaGlkZW4tbWFpbm5ldA
  shibarium: czM6Ly9zaGliYXJpdW0
  shibuya-testnet: czM6Ly9zaGlidXlhLXRlc3RuZXQtdHJhY2VsZXNzLTE
  skale-nebula: czM6Ly9za2FsZS1uZWJ1bGEtdHJhY2VsZXNzLTE
  stratovm-sepolia: czM6Ly9zdHJhdG92bS1zZXBvbGlh
  superseed-sepolia: czM6Ly9zdXBlcnNlZWQtc2Vwb2xpYS10cmFjZWxlc3M
  taiko-mainnet: czM6Ly90YWlrby1tYWlubmV0LXRyYWNlbGVzcw
  tanssi: czM6Ly90YW5zc2ktdHJhY2VsZXNzLTE
  x1-testnet: czM6Ly94MS10ZXN0bmV0LXRyYWNlbGVzcw
  xlayer-mainnet: czM6Ly94bGF5ZXItbWFpbm5ldC10cmFjZWxlc3M
  xlayer-testnet: czM6Ly94bGF5ZXItdGVzdG5ldC10cmFjZWxlc3M
  zksync-mainnet: czM6Ly96a3N5bmMtbWFpbm5ldC0x
  zksync-sepolia: czM6Ly96a3N5bmMtc2Vwb2xpYS0y
  zora-mainnet: czM6Ly96b3JhLW1haW5uZXQ
  zora-sepolia: czM6Ly96b3JhLXNlcG9saWEtdHJhY2VsZXNzLTE
  acala: czM6Ly9hY2FsYS00
  acurast-canary: czM6Ly9hY3VyYXN0LWNhbmFyeQ
  agung: czM6Ly9hZ3VuZy00
  aleph-zero: czM6Ly9hbGVwaC16ZXJv
  aleph-zero-testnet: czM6Ly9hbGVwaC16ZXJvLXRlc3RuZXQ
  amplitude: czM6Ly9hbXBsaXR1ZGUtNA
  asset-hub-kusama: czM6Ly9hc3NldC1odWIta3VzYW1hLTQ
  asset-hub-polkadot: czM6Ly9hc3NldC1odWItcG9sa2Fkb3QtNA
  asset-hub-rococo: czM6Ly9hc3NldC1odWItcm9jb2NvLTQ
  astar-substrate: czM6Ly9hc3Rhci1zdWJzdHJhdGU
  avail: czM6Ly9hdmFpbC0x
  basilisk: czM6Ly9iYXNpbGlzay00
  bifrost-kusama: czM6Ly9iaWZyb3N0LWt1c2FtYS00
  bifrost-polkadot: czM6Ly9iaWZyb3N0LXBvbGthZG90LTQ
  bittensor-testnet: czM6Ly9iaXR0ZW5zb3ItdGVzdG5ldA
  bittensor: czM6Ly9iaXR0ZW5zb3ItNA
  bridge-hub-kusama: czM6Ly9icmlkZ2UtaHViLWt1c2FtYS00
  bridge-hub-polkadot: czM6Ly9icmlkZ2UtaHViLXBvbGthZG90LTQ
  bridge-hub-rococo: czM6Ly9icmlkZ2UtaHViLXJvY29jby00
  bridge-hub-westend: czM6Ly9icmlkZ2UtaHViLXdlc3RlbmQtNA
  centrifuge: czM6Ly9jZW50cmlmdWdlLTQ
  cere: czM6Ly9jZXJlLTQ
  chainflip: czM6Ly9jaGFpbmZsaXAtNA
  collectives-polkadot: czM6Ly9jb2xsZWN0aXZlcy1wb2xrYWRvdC00
  collectives-westend: czM6Ly9jb2xsZWN0aXZlcy13ZXN0ZW5kLTQ
  crust: czM6Ly9jcnVzdC00
  clover: czM6Ly9jbG92ZXItNA
  data-avail: czM6Ly9kYXRhLWF2YWlsLTQ
  dancebox: czM6Ly9kYW5jZWJveC00
  darwinia-crab: czM6Ly9kYXJ3aW5pYS1jcmFiLTQ
  darwinia: czM6Ly9kYXJ3aW5pYS00
  degen-chain: czM6Ly9kZWdlbi10cmFjZWxlc3M
  eden: czM6Ly9lZGVuLTQ
  enjin-matrix: czM6Ly9lbmppbi1tYXRyaXgtNA
  enjin-canary-matrix: czM6Ly9lbmppbi1jYW5hcnktbWF0cml4
  equilibrium: czM6Ly9lcXVpbGlicml1bQ
  foucoco: czM6Ly9mb3Vjb2NvLTU
  frequency: czM6Ly9mcmVxdWVuY3ktNA
  gemini-3h: czM6Ly9nZW1pbmktM2g
  hydradx: czM6Ly9oeWRyYWR4LTQ
  integritee: czM6Ly9pbnRlZ3JpdGVl
  interlay: czM6Ly9pbnRlcmxheS00
  invarch-parachain: czM6Ly9pbnZhcmNoLXBhcmFjaGFpbi00
  invarch-tinkernet: czM6Ly9pbnZhcmNoLXRpbmtlcm5ldC01
  joystream: czM6Ly9qb3lzdHJlYW0tNA
  karura: czM6Ly9rYXJ1cmEtNA
  khala: czM6Ly9raGFsYS00
  kilt: czM6Ly9raWx0LTQ
  kintsugi: czM6Ly9raW50c3VnaS00
  kusama: czM6Ly9rdXNhbWEtNA
  litentry: czM6Ly9saXRlbnRyeS00
  moonbeam-substrate: czM6Ly9tb29uYmVhbS1zdWJzdHJhdGUtNA
  moonbase-substrate: czM6Ly9tb29uYmFzZS1zdWJzdHJhdGUtNA
  moonriver-substrate: czM6Ly9tb29ucml2ZXItc3Vic3RyYXRlLTQ
  paseo: czM6Ly9wYXNlby01
  peaq-mainnet-substrate: czM6Ly9wZWFxLW1haW5uZXQtNQ
  pendulum: czM6Ly9wZW5kdWx1bS00
  phala-testnet: czM6Ly9waGFsYS10ZXN0bmV0LTQ
  phala: czM6Ly9waGFsYS00
  picasso: czM6Ly9waWNhc3Nv
  polimec: czM6Ly9wb2xpbWVjLTQ
  polkadex: czM6Ly9wb2xrYWRleA
  polkadot: czM6Ly9wb2xrYWRvdC00
  polymesh: czM6Ly9wb2x5bWVzaC00
  reef-testnet: czM6Ly9yZWVmLXRlc3RuZXQtNC0x
  reef: czM6Ly9yZWVmLTQ
  robonomics: czM6Ly9yb2Jvbm9taWNzLTQ
  rococo: czM6Ly9yb2NvY28tNA
  rolimec: czM6Ly9yb2xpbWVjLTQ
  shiden-substrate: czM6Ly9zaGlkZW4tc3Vic3RyYXRlLTQ
  shibuya-substrate: czM6Ly9zaGlidXlhLXN1YnN0cmF0ZQ
  sora-mainnet: czM6Ly9zb3JhLW1haW5uZXQtNA
  subsocial-parachain: czM6Ly9zdWJzb2NpYWwtcGFyYWNoYWluLTQtMQ
  ternoa: czM6Ly90ZXJub2EtNA
  turing-avail: czM6Ly9hdmFpbC10dXJpbmc
  turing-mainnet: czM6Ly90dXJpbmctbWFpbm5ldA
  vara: czM6Ly92YXJhLTQ
  vara-testnet: czM6Ly92YXJhLXRlc3RuZXQtNA
  westend: czM6Ly93ZXN0ZW5kLTQ
  zeitgeist-testnet: czM6Ly96ZWl0Z2Vpc3QtdGVzdG5ldC00
  zeitgeist: czM6Ly96ZWl0Z2Vpc3QtNA
  zkverify-testnet: czM6Ly96a3ZlcmlmeS10ZXN0bmV0
