hostname: http://0.0.0.0:8000
available_datasets:
  0g-testnet:
    bucket: s3://0g-testnet-traceless-1
  aleph-zero-evm-mainnet:
    bucket: s3://aleph-zero-evm-mainnet
  arbitrum-nova:
    bucket: s3://arbitrum-nova-1
  arbitrum-one:
    bucket: s3://arbitrum-one
  arbitrum-sepolia:
    bucket: s3://arbitrum-sepolia-traceless
  arthera-mainnet:
    bucket: s3://arthera-mainnet
  astar-mainnet:
    bucket: s3://astar-mainnet-traceless-1
  astar-zkyoto:
    bucket: s3://astar-zkyoto-1-traceless
  astar-zkevm-mainnet:
    bucket: s3://astar-zkevm-mainnet-1-traceless
  avalanche-mainnet:
    bucket: s3://ava-mainnet-1
  avalanche-testnet:
    bucket: s3://ava-testnet-1
  b3-sepolia:
    bucket: s3://b3-sepolia
  b3-mainnet:
    bucket: s3://b3-mainnet
  base-mainnet:
    bucket: s3://base
  base-sepolia:
    bucket: s3://base-sepolia
  berachain-bartio:
    bucket: s3://berachain-bartio
  binance-mainnet:
    bucket: s3://binance-mainnet
  binance-testnet:
    bucket: s3://binance-testnet-traceless-1
  bitfinity-mainnet:
    bucket: s3://bitfinity-mainnet
  bitfinity-testnet:
    bucket: s3://bitfinity-testnet
  blast-l2-mainnet:
    bucket: s3://blast-l2-mainnet-1
  blast-sepolia:
    bucket: s3://blast-sepolia-1-traceless
  bitgert-mainnet:
    bucket: s3://bitgert-mainnet-1
  bitgert-testnet:
    bucket: s3://bitgert-testnet-1
  bob-mainnet:
    bucket: s3://bob-mainnet
  canto:
    bucket: s3://canto-traceless
  canto-testnet:
    bucket: s3://canto-testnet-traceless
  core-mainnet:
    bucket: s3://core-mainnet-1
  cyberconnect-l2-testnet:
    bucket: s3://cyber-l2-testnet-2
  cyber-mainnet:
    bucket: s3://cyber-mainnet-1
  crossfi-testnet:
    bucket: s3://crossfi-testnet-traceless
  dfk-chain:
    bucket: s3://dfk-chain-traceless-1
  dogechain-mainnet:
    bucket: s3://dogechain-mainnet-traceless-1
  dogechain-testnet:
    bucket: s3://dogechain-testnet-traceless-1
  ethereum-holesky:
    bucket: s3://ethereum-holesky-1
  ethereum-mainnet:
    bucket: s3://ethereum-mainnet
  ethereum-sepolia:
    bucket: s3://ethereum-sepolia-1
  etherlink-mainnet:
    bucket: s3://etherlink-mainnet-traceless
  etherlink-testnet:
    bucket: s3://etherlink-testnet-3-traceless
  exosama:
    bucket: s3://exosama-1
  fantom-mainnet:
    bucket: s3://fantom-mainnet-traceless
  fantom-testnet:
    bucket: s3://fantom-testnet-traceless-1
  flare-mainnet:
    bucket: s3://flare-mainnet-traceless-1
  galxe-gravity:
    bucket: s3://galxe-gravity
  gelato-arbitrum-blueberry:
    bucket: s3://arbitrum-blueberry-1
  gelato-opcelestia-raspberry:
    bucket: s3://opcelestia-raspberry-traceless
  gnosis-mainnet:
    bucket: s3://gnosis-mainnet-1
  immutable-zkevm-mainnet:
    bucket: s3://immutable-zkevm-mainnet-traceless-1
  immutable-zkevm-testnet:
    bucket: s3://immutable-zkevm-testnet-traceless-1
  kyoto-testnet:
    bucket: s3://kyoto-testnet-traceless
  linea-mainnet:
    bucket: s3://linea-mainnet-1
  manta-pacific:
    bucket: s3://manta-pacific-traceless
  manta-pacific-sepolia:
    bucket: s3://manta-pacific-sepolia
  mantle-mainnet:
    bucket: s3://mantle-mainnet-1-traceless
  mantle-sepolia:
    bucket: s3://mantle-sepolia-1-traceless
  merlin-mainnet:
    bucket: s3://merlin-mainnet-traceless
  merlin-testnet:
    bucket: s3://merlin-testnet-traceless
  metis-mainnet:
    bucket: s3://metis-mainnet-3
  mode-mainnet:
    bucket: s3://mode-mainnet-traceless
  moonbase-testnet:
    bucket: s3://moonbase-testnet-1
  moonbeam-mainnet:
    bucket: s3://moonbeam-evm-2
  moonriver-mainnet:
    bucket: s3://moonriver-mainnet-1
  moonsama:
    bucket: s3://moonsama-traceless-1
  nakachain:
    bucket: s3://nakachain
  neon-mainnet:
    bucket: s3://neon-mainnet-traceless
  neon-devnet:
    bucket: s3://neon-devnet-traceless-1
  neox-testnet:
    bucket: s3://neox-testnet
  opbnb-mainnet:
    bucket: s3://opbnb-mainnet-traceless-1
  opbnb-testnet:
    bucket: s3://opbnb-testnet-traceless-1
  optimism-mainnet:
    bucket: s3://optimism-2
  optimism-sepolia:
    bucket: s3://optimism-sepolia-traceless
  peaq-mainnet:
    bucket: s3://peaq-mainnet-traceless-1
  plume-testnet:
    bucket: s3://plume-testnet
  plume-devnet:
    bucket: s3://plume-devnet
  polygon-mainnet:
    bucket: s3://polygon-mainnet-1
  polygon-amoy-testnet:
    bucket: s3://polygon-amoy-testnet-traceless
  polygon-zkevm-mainnet:
    bucket: s3://polygon-zkevm-mainnet-traceless
  polygon-zkevm-cardona-testnet:
    bucket: s3://polygon-zkevm-cardona-testnet-traceless-1
  prom-testnet:
    bucket: s3://prom-testnet-1-traceless
  prom-testnet-v2:
    bucket: s3://prom-testnet-v2
  puppynet:
    bucket: s3://puppynet
  scroll-mainnet:
    bucket: s3://scroll-mainnet
  scroll-sepolia:
    bucket: s3://scroll-sepolia
  shiden-mainnet:
    bucket: s3://shiden-mainnet
  shibarium:
    bucket: s3://shibarium
  shibuya-testnet:
    bucket: s3://shibuya-testnet-traceless-1
  skale-nebula:
    bucket: s3://skale-nebula-traceless-1
  stratovm-sepolia:
    bucket: s3://stratovm-sepolia
  superseed-sepolia:
    bucket: s3://superseed-sepolia-traceless
  taiko-mainnet:
    bucket: s3://taiko-mainnet-traceless
  tanssi:
    bucket: s3://tanssi-traceless-1
  x1-testnet:
    bucket: s3://x1-testnet-traceless
  xlayer-mainnet:
    bucket: s3://xlayer-mainnet-traceless
  xlayer-testnet:
    bucket: s3://xlayer-testnet-traceless
  zksync-mainnet:
    bucket: s3://zksync-mainnet-1
  zksync-sepolia:
    bucket: s3://zksync-sepolia-2
  zora-mainnet:
    bucket: s3://zora-mainnet
  zora-sepolia:
    bucket: s3://zora-sepolia-traceless-1
  acala:
    bucket: s3://acala-4
  acurast-canary:
    bucket: s3://acurast-canary
  agung:
    bucket: s3://agung-4
  aleph-zero:
    bucket: s3://aleph-zero
  aleph-zero-testnet:
    bucket: s3://aleph-zero-testnet
  amplitude:
    bucket: s3://amplitude-4
  asset-hub-kusama:
    bucket: s3://asset-hub-kusama-4
  asset-hub-polkadot:
    bucket: s3://asset-hub-polkadot-4
  asset-hub-rococo:
    bucket: s3://asset-hub-rococo-4
  astar-substrate:
    bucket: s3://astar-substrate
  avail:
    bucket: s3://avail-1
  basilisk:
    bucket: s3://basilisk-4
  bifrost-kusama:
    bucket: s3://bifrost-kusama-4
  bifrost-polkadot:
    bucket: s3://bifrost-polkadot-4
  bittensor-testnet:
    bucket: s3://bittensor-testnet
  bittensor:
    bucket: s3://bittensor-4
  bridge-hub-kusama:
    bucket: s3://bridge-hub-kusama-4
  bridge-hub-polkadot:
    bucket: s3://bridge-hub-polkadot-4
  bridge-hub-rococo:
    bucket: s3://bridge-hub-rococo-4
  bridge-hub-westend:
    bucket: s3://bridge-hub-westend-4
  centrifuge:
    bucket: s3://centrifuge-4
  cere:
    bucket: s3://cere-4
  chainflip:
    bucket: s3://chainflip-4
  collectives-polkadot:
    bucket: s3://collectives-polkadot-4
  collectives-westend:
    bucket: s3://collectives-westend-4
  crust:
    bucket: s3://crust-4
  clover:
    bucket: s3://clover-4
  data-avail:
    bucket: s3://data-avail-4
  dancebox:
    bucket: s3://dancebox-4
  darwinia-crab:
    bucket: s3://darwinia-crab-4
  darwinia:
    bucket: s3://darwinia-4
  degen-chain:
    bucket: s3://degen-traceless
  eden:
    bucket: s3://eden-4
  enjin-matrix:
    bucket: s3://enjin-matrix-4
  enjin-canary-matrix:
    bucket: s3://enjin-canary-matrix
  equilibrium:
    bucket: s3://equilibrium
  foucoco:
    bucket: s3://foucoco-5
  frequency:
    bucket: s3://frequency-4
  gemini-3h:
    bucket: s3://gemini-3h
  hydradx:
    bucket: s3://hydradx-4
  integritee:
    bucket: s3://integritee
  interlay:
    bucket: s3://interlay-4
  invarch-parachain:
    bucket: s3://invarch-parachain-4
  invarch-tinkernet:
    bucket: s3://invarch-tinkernet-5
  joystream:
    bucket: s3://joystream-4
  karura:
    bucket: s3://karura-4
  khala:
    bucket: s3://khala-4
  kilt:
    bucket: s3://kilt-4
  kintsugi:
    bucket: s3://kintsugi-4
  kusama:
    bucket: s3://kusama-4
  litentry:
    bucket: s3://litentry-4
  moonbeam-substrate:
    bucket: s3://moonbeam-substrate-4
  moonbase-substrate:
    bucket: s3://moonbase-substrate-4
  moonriver-substrate:
    bucket: s3://moonriver-substrate-4
  paseo:
    bucket: s3://paseo-5
  peaq-mainnet-substrate:
    bucket: s3://peaq-mainnet-5
  pendulum:
    bucket: s3://pendulum-4
  phala-testnet:
    bucket: s3://phala-testnet-4
  phala:
    bucket: s3://phala-4
  picasso:
    bucket: s3://picasso
  polimec:
    bucket: s3://polimec-4
  polkadex:
    bucket: s3://polkadex
  polkadot:
    bucket: s3://polkadot-4
  polymesh:
    bucket: s3://polymesh-4
  reef-testnet:
    bucket: s3://reef-testnet-4-1
  reef:
    bucket: s3://reef-4
  robonomics:
    bucket: s3://robonomics-4
  rococo:
    bucket: s3://rococo-4
  rolimec:
    bucket: s3://rolimec-4
  shiden-substrate:
    bucket: s3://shiden-substrate-4
  shibuya-substrate:
    bucket: s3://shibuya-substrate
  sora-mainnet:
    bucket: s3://sora-mainnet-4
  subsocial-parachain:
    bucket: s3://subsocial-parachain-4-1
  ternoa:
    bucket: s3://ternoa-4
  turing-avail:
    bucket: s3://avail-turing
  turing-mainnet:
    bucket: s3://turing-mainnet
  vara:
    bucket: s3://vara-4
  vara-testnet:
    bucket: s3://vara-testnet-4
  westend:
    bucket: s3://westend-4
  zeitgeist-testnet:
    bucket: s3://zeitgeist-testnet-4
  zeitgeist:
    bucket: s3://zeitgeist-4
  zkverify-testnet:
    bucket: s3://zkverify-testnet
