logs_collector_id: "12D3KooWC3GvQVqnvPwWz23sTW8G8HVokMnox62A7mnL9wwaSujk"
send_metrics: true
worker_inactive_threshold_sec: 120
worker_greylist_time_sec: 1800
default_query_timeout_sec: 60
summary_print_interval_sec: 30
workers_update_interval_sec: 180
available_datasets:
  arbitrum-one: "czM6Ly9hcmJpdHJ1bS1vbmU"
  ethereum-mainnet: "czM6Ly9ldGhlcmV1bS1tYWlubmV0"
  binance-mainnet: "czM6Ly9iaW5hbmNlLW1haW5uZXQ"
  zksync-mainnet: "czM6Ly96a3N5bmMtbWFpbm5ldC0x"
