name: docker
on:
  workflow_dispatch: # manually run
    inputs:
      tag:
        description: image tag
        required: true

env:
  CI: true

jobs:
  publish:
    name: Build & publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build query gateway
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: subsquid/query-gateway:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get query gateway version
        run: echo "GATEWAY_VERSION=$(docker run --rm subsquid/query-gateway:test subsquid-query-gateway --version | cut -d ' ' -f2)" >> $GITHUB_ENV

      - name: Build & publish query gateway
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: |
            subsquid/query-gateway:${{ env.GATEWAY_VERSION }}
            subsquid/query-gateway:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
